# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
restartPolicy: Always

env:
  AUTH_API_ADDRESS: http://auth-api:8081
  PORT: "8080"
  TODOS_API_ADDRESS: http://todos-api:8082
  ZIPKIN_URL: http://zipkin:9411/api/v2/spans

image:
  repository: sgilz/workshop-frontend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "frontend"
fullnameOverride: "workshop-frontend"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
