# Default values for zipkin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: ${zipkin_replicaCount}
restartPolicy: ${zipkin_restartPolicy}

env:
  ${zipkin_env_vars}

image:
  repository: ${zipkin_registry}
  tag: latest
  pullPolicy: ${zipkin_pull_policy}

nameOverride: ${zipkin_short_name}
fullnameOverride: ${zipkin_long_name}

service:
  type: ClusterIP
  port: ${zipkin_port}
