# Default values for log_msg_proc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: ${log_msg_proc_replicaCount}
restartPolicy: ${log_msg_proc_restartPolicy}

env:
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}
  REDIS_CHANNEL: log_channel
  ZIPKIN_URL: ${ZIPKIN_URL}

image:
  repository: ${log_msg_proc_registry}
  tag: latest
  pullPolicy: ${log_msg_proc_pull_policy}

nameOverride: ${log_msg_proc_short_name}
fullnameOverride: ${log_msg_proc_long_name}
