apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "users-api.name" . }}
    helm.sh/chart: {{ include "users-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "users-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "users-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env }}
          - { name: "{{$key}}", value: "{{$value}}" }
          {{end}}
          {{end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /users
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /users
          #     port: http
      restartPolicy: {{ .Values.restartPolicy }}
