# Default values for users-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
restartPolicy: Always

env:
  JWT_SECRET: myfancysecret
  SERVER_PORT: "8083"
  SPRING_ZIPKIN_BASE_URL: http://zipkin:9411

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: "users-api"
fullnameOverride: "workshop-users-api"

service:
  type: ClusterIP
  port: 8083
