apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-queue.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "redis-queue.name" . }}
    helm.sh/chart: {{ include "redis-queue.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redis-queue.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "redis-queue.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          - env:
          {{- range $key, $value := .Values.env }}
          - { name: "{{$key}}", value: "{{$value}}" }
          {{end}}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
            command: ["redis-cli", "ping"]
          readinessProbe:
            exec:
            command: ["redis-cli", "ping"]
      restartPolicy: {{ .Values.restartPolicy }}
